# defaults:
#   -
#     scope:
#       path: ""      # empty string for all files
#       type: posts   # limit to posts
#     values:
#       is_post: true # automatically set is_post=true for all posts


title: /tmp/being
email: your-email@example.com
description: Thoughts on software and humanity
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://planelles.dev"
github_username:  tmpbeing
timezone: Europe/Paris
future: true
permalink: blog/:year/:month/:day

# Build settings
markdown: kramdown
highlighter: rouge
