# defaults:
#   -
#     scope:
#       path: ""      # empty string for all files
#       type: posts   # limit to posts
#     values:
#       is_post: true # automatically set is_post=true for all posts


title: /tmp/being
description: Thoughts on software, productivity and society
baseurl: /
url: "https://planelles.dev"
github_username:  tmpbeing
timezone: Europe/Paris
future: true
permalink: blog/:year/:month/:day

# Build settings
markdown: kramdown
highlighter: rouge
